[project]
name = "grad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "graphviz>=0.21",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "nbconvert>=7.16.6",
    "scikit-learn>=1.7.0",
]
